name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Build_APK:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
     # working-directory: ./FolderName  #Uncomment me - if your gradle file is inside a folder
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

  Instrumental_Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
      # working-directory: ./FolderName  #Uncomment me - if your gradle file is inside a folder
        run: chmod +x gradlew
      - name: Instrumentation Tests
      # working-directory: ./FolderName  #Uncomment me - if your gradle file is inside a folder
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          script: ./gradlew connectedAndroidTest

  Unit_Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
      # working-directory: ./FolderName  #Uncomment me - if your gradle file is inside a folder
        run: chmod +x gradlew
      - name: Unit tests
      # working-directory: ./FolderName  #Uncomment me - if your gradle file is inside a folder
        run: ./gradlew test
        

  Generate_Docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Generate API documentation
      if: ${{github.event_name == 'push'}}
      run: ./gradlew dokkaHtml
    - name: Deploy API documentation to Github Pages
      if: ${{github.event_name == 'push'}}
      uses: peaceiris/actions-gh-pages@v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        BRANCH: gh-pages
        publish_dir: ./app/build/dokka/html # specify the 
      # builds zip file with kdoc website inside
    - name: Archive KDoc Documentation
      uses: actions/upload-artifact@v2
      with:
          name: KDoc Documentation Site
          path: app/build/dokka/html
