name: Docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Generate API documentation
      if: ${{github.event_name == 'push'}}
      run: ./gradlew dokkaHtml
    - name: Deploy API documentation to Github Pages
      if: ${{github.event_name == 'push'}}
      uses: peaceiris/actions-gh-pages@v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        BRANCH: gh-pages
        publish_dir: ./app/build/dokka/html
      # builds zip file with kdoc website inside
    - name: Archive KDoc Documentation
      uses: actions/upload-artifact@v2
      with:
          name: KDoc Documentation Site
          path: app/build/dokka/html
